### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by syjer** [alfio-event/alf.io-public-frontend#1]
- [ ] error handling (especially for the payment section)
- [ ] check: additional options availability messages in UI
- [ ] check show-event.ms : showNoCategoriesWarning, containsExpiredCategories
- [ ] stripe payment: we have still commented the address part in stripe-payment-proxy.component.ts (`/*address: {`) see https://github.com/alfio-event/alf.io-public-frontend/blob/master/src/app/payment/stripe-payment-proxy/stripe-payment-proxy.component.ts#L238   

Additional fields:
- [ ] handle euVat correctly (!check)
- [ ] required/min/max length

note:

use of showNoCategoriesWarning :
https://github.com/alfio-event/alf.io/blob/2.0-M1-maintenance/src/main/webapp/WEB-INF/templates/event/show-event.ms#L125

use of containsExpiredCategories: 
https://github.com/alfio-event/alf.io/blob/2.0-M1-maintenance/src/main/webapp/WEB-INF/templates/event/show-event.ms#L130

**Comment by syjer** [comment]
Additional fields:

- [ ] handle the various type
- [ ] handle euVat correctly (!check)
- [ ] multi language support
- [ ] required/min/max length
- [ ] label for/id
